name: Preview PR

on:
  push:
    branches:
      - '!main'
      - '!gh-pages'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  workflow_dispatch:
    inputs:
      whotriggered:
        description: 'Manual Trigger'
        default: 'Trigger manually'
        required: false

concurrency: preview-${{ github.ref }}

permissions:
  pages: write
  id-token: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Update Data
        run: |
          python pulse/app.py -c configs/config.json
          # git config --local user.email "action@github.com"
          # git config --local user.name "GitHub Action"
          # git pull
          # git status
          # git add .
          # git commit -m "Update Social Pulse Data" || echo "Nothing to update"
          # git config pull.rebase true
          # git pull
          # git status
          # git push
      - name: Move Data
        run: |
          sh move_data.sh
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: build
        env:
          # BASE_PATH: '/${{ github.event.repository.name }}'
          BASE_PATH: '/'
          ## Add and uncomment any environment variables here
          ## EVIDENCE_SOURCE__my_source__username: ${{ secrets.EVIDENCE_SOURCE__MY_SOURCE__USERNAME }}
          ## EVIDENCE_SOURCE__my_source__private_key: ${{ secrets.EVIDENCE_SOURCE__MY_SOURCE__PRIVATE_KEY }}
        run: |
          npm run sources
          npm run build
      - name: CNAME
        run: |
          echo 'pulse.leima.is' > build/CNAME
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1.4.7
        with:
          source-dir: ./build/
